### ISSUE TITLE
Design an opt-in/opt-out workflow

### ISSUE THREAD

**Issue by jennpb** [wellcometrust/wellcomecollection.org#3739] opened 2018-11-18 19:07 UTC
## Who it's for
- Website users (internal or external) who agree to use features/functionality in development

## Problem to solve
How to get people to self-select into a toggled cohort, and how to let them get out of it again

**Comment by Heesoomoon** [comment] 2018-12-06 21:30
I'll sketch out few options for us to review next week.

**Comment by jamesgorrie** [comment] 2018-12-07 09:56
@Heesoomoon would it be good to talk about what we're trying to do, maybe some examples etc, before coming up with the solution (he says after building one)?

**Comment by jamesgorrie** [comment] 2019-01-16 08:42
Potential duplicate of #3959?

**Comment by Heesoomoon** [comment] 2019-01-16 15:21
@jennpb Could we close this and keep #3959?

**Closed** 2019-01-17 10:01 UTC
Labels: feature, needs:refinement
