### ISSUE TITLE
Build exhibition list page

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1862] opened 2017-11-27 11:57 UTC
Dev tasks for just the exhibitions part of #1796

## Type
- ✨ Feature

- [ ] Create a page
- [ ] Fetch all current exhibitions and display on the page
- [ ] Apply visual design

**Comment by jamesgorrie** [comment] 2017-11-28 11:03
Closing as duplicate of #1796

**Closed by jamesgorrie** 2017-11-28 11:03 UTC
