### ISSUE TITLE
Design nit: pluralisation in IIIF Presentation views/galleries

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#4843] opened 2019-11-05 21:47 UTC
When you're looking at a gallery/IIIF manifest with a single image, the text says “1 images”. An incredibly picky person would suggest this should be “1 image” instead.

![Screenshot 2019-11-05 at 21 36 05](https://user-images.githubusercontent.com/301220/68248759-5fcff980-0015-11ea-978a-21055b8f7770.png)

I think this is the code in question:

https://github.com/wellcometrust/wellcomecollection.org/blob/80772321dccfecca96913b5d07344e2b25bd777b/common/views/components/ImageGallery/ImageGallery.js#L288

https://github.com/wellcometrust/wellcomecollection.org/blob/df61793f5cd9352923da2c422cd5fe672050c4ce/common/views/components/IIIFPresentationPreview/IIIFPresentationPreview.js#L387-L391

I think you'd also get "1 volumes", if such a work exists.

**Comment by jamesgorrie** [comment] 2019-11-06 08:47
@alexwlchan thanks for the bug report (not nit) - could you please leave links to the works to help us with this please?

**Comment by pollecuttn** [comment] 2019-11-06 09:21
Closing as dupe of https://github.com/wellcometrust/wellcomecollection.org/issues/4529

**Closed by pollecuttn** 2019-11-06 09:21 UTC

**Comment by alexwlchan** [comment] 2019-11-06 09:24
> could you please leave links to the works to help us with this please?

dang it, forgot to add it

https://wellcomecollection.org/works/uktaupjd
