### ISSUE TITLE
Build license info component

### ISSUE THREAD

**Issue by davidpmccormick** [wellcometrust/wellcomecollection.org#1138] opened 2017-07-10 09:44 UTC
## Type
- ✨ Feature

## UI Requirements
![screen shot 2017-07-10 at 10 39 05](https://user-images.githubusercontent.com/1394592/28011993-4803d4b2-655c-11e7-8643-c0e89a914c9f.png)

- [x] Word/related icons for all possible licenses

## Acceptance Criteria

- [x] The interface should be able display appropriate icons and text for all licenses

## Problem to be solved / User Story
In order to
 _understand how I should cite this material_

As a
 _user_

I need/want/expect 
_to see clear licensing information on the item page_

**Comment by jennpb** [comment] 2017-07-11 07:24
Could we try a variant with the CC BY spelled out like they do on Soundcloud? `Creative Commons License`
https://soundcloud.com/wellcomelibrary/diagnosis-of-a-depressive-illness-in-general-practice

**Comment by gestchild** [comment] 2017-07-13 14:03
@jennpb do you have a list of the licenses we need to cater for? thanks

**Comment by jennpb** [comment] 2017-07-14 09:30
@gestchild 
CC0
CC BY
CC BY NC
CC BY NC ND
PDM
Copyright not cleared

I don't think we have any SAs.

**Comment by gestchild** [comment] 2017-07-17 09:47
Duplicate of #1078

**Closed** 2017-07-17 09:46 UTC
