### ISSUE TITLE
“Galleries” tab in the Opening Times panel is reduced-width

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/wellcomecollection.org#491] opened 2017-02-09 13:59 UTC
If you look at the tabs in the Opening Times panel, there’s a decent chunk of padding either side of the label – except for “Galleries”, in which the label is flush left and the left padding is zero.

Effect is that it looks smaller than the rest, and you don’t see the left border of the tab – the only tab for which that’s the case.

![screen shot 2017-02-09 at 13 59 09](https://cloud.githubusercontent.com/assets/301220/22786330/fb74f6d8-eecf-11e6-99a1-ea37089b1a85.png)

Safari 10.0.1.

**Comment by gestchild** [comment] 2017-02-09 14:05
That is how it was designed

**Comment by jamesgorrie** [comment] 2017-02-09 15:51
CLosing as not a bug

**Closed by jamesgorrie** 2017-02-09 15:51 UTC

**Comment by alexwlchan** [comment] 2017-02-09 18:07
I think this would be classified "Working As Designed". :-)
