### ISSUE TITLE
Logo cutoff

### ISSUE THREAD

**Issue by jamesgorrie** [wellcometrust/wellcomecollection.org#339] opened 2017-01-19 09:39 UTC
Chrome, Android, Nexus 5X

![screenshot_20170119-093721](https://cloud.githubusercontent.com/assets/31692/22101394/1e34ae9e-de2b-11e6-98e8-840e687aa8b6.png)

**Comment by davidpmccormick** [comment] 2017-01-20 10:18
Closing as duplicate of #359.

**Closed by davidpmccormick** 2017-01-20 10:18 UTC
Labels: duplicate
