### ISSUE TITLE
User Research: Book Viewer enhancement

### ISSUE THREAD

**Issue by Heesoomoon** [wellcometrust/wellcomecollection.org#4524] opened 2019-06-12 16:20 UTC
After launching #4325 'Book viewer enhancements', we want to monitor and get user feedback on following areas:

**Workflow**
- Does new workflow (Works>Thumbnail list>Detail view) support their research mode?
- How do they expect to find relevant info? e.g. author, year, etc.
- Does the workflow work for items with multiple images? e.g. ephemera, paintings, etc.

**Thumbnail List**
- What's the impression of the list? Do we need to refine the size of the images or # of images we display?
- Do they recognize currently selected pages?
- What information about the work might they need to reference from this view? #4444 

**Detail View**
- Do they know how to navigate back to the thumbnail view?
- Observe how users discover and interact with view controls (Zoom in/out, Previous/Next pages)
- User expectation of Zoom controls and # of levels
- What information about the work might they need to reference from this view? #4444

**Comment by Heesoomoon** [comment] 2019-06-18 08:53
@jennpb Re: the size of the thumbnail images, we've heard how people felt "overwhelmed" when we present too many pages on the screen. 

The current thumbnail size feels a bit too small to visually recognise the type of the page and too many pages to process at a glance. The sizing on Alpha feels more manageable. I don't think we need user research on this but enhance based on our past research insights.

[Current implementation
](https://wellcomecollection.org/works/enws5rhq/items?sierraId=b29299536&langCode=eng&canvas=19)
![Screen Shot 2019-06-18 at 09 47 02](https://user-images.githubusercontent.com/29206031/59667307-649f2880-91ae-11e9-8900-b0f42fc9c94d.png)

[Alpha](https://alpha.wellcomelibrary.org/b20595207)
![Screen Shot 2019-06-18 at 09 47 18](https://user-images.githubusercontent.com/29206031/59667159-2b66b880-91ae-11e9-978c-b2503e5a762c.png)

**Comment by Heesoomoon** [comment] 2019-06-21 14:06
**Update:**
Recommend doing un-moderated usability research for the book viewer CTAs using 'Verify App'.

Current implementation vs. 'Tab' idea
Here's one way to simplify the interaction of the view toggle and download using familiar visual UI for different actions. It's implying the page view is in the background and these three states are layered on top to provide more info, navigate to other pages or save the item.

**Thumbnail list**
![Viewer_List](https://user-images.githubusercontent.com/29206031/59690890-11db6600-91da-11e9-8699-fc3b68930c97.png)

**Item info**
![Viewer_Info](https://user-images.githubusercontent.com/29206031/59688880-7b597580-91d6-11e9-9856-c5442cdc6cee.png)

**Download**
![Viewer_Download](https://user-images.githubusercontent.com/29206031/59688876-7b597580-91d6-11e9-9c01-eb47df4aadb9.png)

**Comment by jennpb** [comment] 2019-09-18 07:26
Now duplicate of #4728 so closing

**Closed by jennpb** 2019-09-18 07:26 UTC
Labels: needs:research
